print("Hello there! What is your name:")
name = input()
print("Hello "+name)
print("How old are you?")
age = input()
birth_year = 2022-int(age)
st_year = str(birth_year)
print("You are born in "+st_year)
